#!/bin/bash

GO_PATH=$(pwd)
GO_BIN=$GO_PATH/bin

export GOPATH=$GO_PATH
export GOBIN=$GO_BIN

export GIT_COMMIT=$(git rev-list -1 HEAD)
cd src/docker_rdma_sriov
CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-X main.GitCommitId=$GIT_COMMIT -extldflags "-static"" -o bin/docker_rdma_sriov docker_rdma_sriov
